hashicorp:
  daemons:
    - vault
    - consul
    - nomad
  tools:
    terraform: 0.13.0
    consul-template: 0.25.1
    consul: 1.8.3
    vault: 1.5.0
    nomad: 0.12.3
    packer: 1.6.1
  tools_enterprise:
    consul: 1.8.3+ent
    nomad: 0.12.3+ent
    vault: 1.5.0+ent
ansible:
  galaxy:
    roles:
      - geerlingguy.docker
docker_users:
  - vagrant
