hashicorp:
  daemons:
    - consul
    - nomad
    - vault
  tools:
    terraform: 0.12.26
    consul-template: 0.25.0
    consul: 1.8.0
    vault: 1.4.2
    nomad: 0.11.3
    packer: 1.6.0
ansible:
  galaxy:
    roles:
      - geerlingguy.docker
docker_users:
  - vagrant