---
- hosts: all
  become: yes
  vars:
    daemons:
      - vault
      - consul
      - nomad
  tasks:
    - name: Running prestart books
      include: "{{ item }}"
      with_fileglob: "prestart/*"

    - name: "Start hashistack"
      systemd: name={{item}} state=started
      loop: "{{ daemons }}"

    - name: Wait for consul to start
      uri:
        url: http://127.0.0.1:8500/ui/dc1/services
        status_code: 200
      register: result
      until: result.status == 200
      retries: 60
      delay: 1

    - name: Wait for nomad to start
      uri:
        url: http://127.0.0.1:4646/v1/jobs
        status_code: 200
      register: result
      until: result.status == 200
      retries: 60
      delay: 1

    - name: Wait for vault to start
      uri:
        url: http://127.0.0.1:8200/ui/
        status_code: 200
      register: result
      until: result.status == 200
      retries: 60
      delay: 1

    - name: Running poststart books
      include: "{{ item }}"
      with_fileglob: "poststart/*"
